// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// DestinationOperations is an autogenerated mock type for the DestinationOperations type
type DestinationOperations struct {
	mock.Mock
}

// Path provides a mock function with no fields
func (_m *DestinationOperations) Path() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Path")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewDestinationOperations creates a new instance of DestinationOperations. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDestinationOperations(t interface {
	mock.TestingT
	Cleanup(func())
}) *DestinationOperations {
	mock := &DestinationOperations{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
